title: ShadowCreator250 @ GitHub
author:
  name: ShadowCreator250
  email: shadowcreator250+github@gmail.com

theme: minima
minima:
  date_format: "%d.%m.%Y, %H:%M:%S"
  social_links:
    github: ShadowCreator250
    youtube_channel_name: ShadowCreator250
