theme: minima
title: ShadowCreator250 @ GitHub
author:
  name: ShadowCreator250
  email: shadowcreator250+github@gmail.com

minima:
  date_format: "%d.%m.%Y, %H:%M:%S"
  social_links:
    github: SHadowCreator250
    youtube_channel_name: SHadowCreator250
